### ISSUE TITLE
BUG: Unable to allocate memory numpy exception

### ISSUE THREAD

**Issue by KappaGi** [morph-kgc/morph-kgc#144]
Hello,

I am trying to generate triplets from a postgres database but I am getting the following error:

> INFO | 2023-01-27 15:16:07,587 | 1 mapping rules retrieved.
INFO | 2023-01-27 15:16:07,594 | Mapping partition with 1 groups generated.
INFO | 2023-01-27 15:16:07,594 | Maximum number of rules within mapping group: 1.
INFO | 2023-01-27 15:16:07,595 | Mappings processed in 0.287 seconds.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/morph_kgc/__main__.py", line 51, in <module>
    num_triples += _materialize_mapping_group_to_file(mapping_group, mappings_df, config)
  File "/usr/local/lib/python3.8/site-packages/morph_kgc/materializer.py", line 371, in _materialize_mapping_group_to_file
    data = _materialize_mapping_rule(mapping_rule, mappings_df, config)
  File "/usr/local/lib/python3.8/site-packages/morph_kgc/materializer.py", line 342, in _materialize_mapping_rule
    data = _get_data(config, mapping_rule, references)
  File "/usr/local/lib/python3.8/site-packages/morph_kgc/materializer.py", line 52, in _get_data
    data = _preprocess_data(data, mapping_rule, references, config)
  File "/usr/local/lib/python3.8/site-packages/morph_kgc/materializer.py", line 37, in _preprocess_data
    data = data.astype(str)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/generic.py", line 6240, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 448, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 352, in apply
    applied = getattr(b, f)(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 526, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 299, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 227, in astype_array
    values = values.astype(dtype, copy=copy)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/arrays/string_.py", line 452, in astype
    return super().astype(dtype, copy)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/arrays/base.py", line 610, in astype
    return np.array(self, dtype=dtype, copy=copy)
numpy.core._exceptions.MemoryError: Unable to allocate 34.7 GiB for an array with shape (291842,) and data type <U31880

when trying to generate triplets according to the following mapping file:

```
<#StudyDetailsView> rr:sqlQuery """ SELECT s.nct_id, d.description FROM studies s JOIN detailed_descriptions d ON (s.nct_id=d.nct_id); """.

<#TriplesMap2>
    rr:logicalTable <#StudyDetailsView>;
    rr:subjectMap [
        rr:template "http://example.com/study/{nct_id}";
    ];
	rr:predicateObjectMap [
		rr:predicate rdfs:comment;
		rr:objectMap [rr:column "description"];
    ]
```
From a postgres database having the following information about the used tables:

```
detailed_descriptions | heap | 421 MB
studies | heap | 248 MB
```

And having default engine parameters in my config. I can generate triplets with other kind of mappings. Specifically with this, I don't know why it is trying to allocate such amount of memory. I tried also with config `number_of_processes: 1` but got the same error. Is this the usual behavior? Is morph asking for more dedicated memory? Why does it need such amount of memory?

Regards.

Environment:
 - OS: Ubuntu 22.04 LTS
 - Python version: 3.8
 - Morph-KGC version: 2.3.1

**Comment by arenas-guerrero-julian** [comment]
Hi @KappaGi 

Because you are using an R2RML view with a JOIN, the resulting logical table (resulting from executing the query) may be much larger. What is the size of the result set of the SQL query? also, how much RAM does your system have?

**Comment by arenas-guerrero-julian** [comment]
This might be caused by overcommit handling in Linux as suggested [here](https://stackoverflow.com/questions/57507832/unable-to-allocate-array-with-shape-and-data-type#answer-57511555). You can try this solution.

**Comment by arenas-guerrero-julian** [comment]
I assume that the suggested solution fixed the issue.

**Comment by KappaGi** [comment]
> I assume that the suggested solution fixed the issue.

Thanks Julian, changing the overcommit mode solved the issue. The mapping might not be the more realistic given the SQL query but it was helpful.

After changing the overcommit mode and run with several processes led to #26. When running in a single process, it gets killed due to memory consumption so the only solution fot me is to have more dedicated memory.

Regards.
