### ISSUE TITLE
QST: syntax for using the function morph-kgc:uuid as part of a URI template in subject map

### ISSUE THREAD

**Issue by mikel-egana-aranguren** [morph-kgc/morph-kgc#179]
Hi;

I'm transforming a CSV to RDF with morph-kgc (Great tool, btw!) and in order to create the subject URIs I need to generate URIs that append UUIDs to a given template, i.e. something along the lines of:

```
<#CustomerMapping> a rr:TriplesMap;
	rml:logicalSource [
		rml:source "Customers.csv";
		rml:referenceFormulation ql:CSV;
	];
	
	rr:subjectMap [
		rr:template "https://data.eus/customer/<#Execution>";
		rr:class vocab:Customer
	].

<#Execution>
    rml:function morph-kgc:uuid .
```

The above mapping does not work, so I would like to know what would be the exact syntax to append the result of the `<#Execution>` (The new UUID) to the `rr:template` base URI ("https://data.eus/customer/"), or if that is even possible. 

Thanks

**Comment by arenas-guerrero-julian** [comment]
Thanks @mikel-egana-aranguren ,

You have to use a nested rule, the mapping should look (I created a random example) like this:

```ttl
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix ex: <http://example.com/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rml: <http://w3id.org/rml/> .
@prefix fno: <https://w3id.org/function/ontology#> .
@prefix morph-kgc: <https://github.com/morph-kgc/morph-kgc/function/built-in.ttl#> .
@prefix grel: <http://users.ugent.be/~bjdmeest/function/grel.ttl#> .
@prefix idlab-fn: <http://example.com/idlab/function/> .

<#CustomerMapping> a rml:TriplesMap;
	rml:logicalSource [
		rml:source "data.csv";
	];
	
	rml:subjectMap [
		rml:functionExecution <#Execution1>;
	];
	rml:predicateObjectMap [
                rml:predicate foaf:name;
                rml:objectMap [
                      rml:reference "Name" ;
                ]
    ] .


<#Execution1>
    rml:function morph-kgc:concat ;
    rml:input
        [
            rml:parameter grel:valueParam1 ;
            rml:inputValueMap [
                rml:constant "https://data.eus/customer/"
            ];
        ] ,
        [
            rml:parameter grel:valueParam2 ;
            rml:inputValueMap [
                rml:functionExecution <#Execution2>
            ];
        ] .

<#Execution2>
    rml:function morph-kgc:uuid .
```

And some example CSV data for the mapping:

```
Id,Name,Comment,Class
1,M Venus,A&B,A
```

**Comment by mikel-egana-aranguren** [comment]
Thanks for the prompt response. 

I have tried to reproduce your example locally but I get a `KeyError: 'object_map'` exception. I paste my local setting and the exception at the end, as follows.

**Python program to generate RDF graph**
```python
import morph_kgc
import rdflib

graph = morph_kgc.materialize('uui-test.ini')
graph.serialize(destination='uui-test.nt', format='ntriples', encoding="utf-8")
```
**uui-test.ini file**
```ini
[DataSourceCSV]
mappings=uui-test.ttl
```

**uui-test.ttl mapping file**
```turtle
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix ex: <http://example.com/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rml: <http://w3id.org/rml/> .
@prefix fno: <https://w3id.org/function/ontology#> .
@prefix morph-kgc: <https://github.com/morph-kgc/morph-kgc/function/built-in.ttl#> .
@prefix grel: <http://users.ugent.be/~bjdmeest/function/grel.ttl#> .
@prefix idlab-fn: <http://example.com/idlab/function/> .

<#CustomerMapping> a rml:TriplesMap;
	rml:logicalSource [
		rml:source "uui-test.csv";
	];
	
	rml:subjectMap [
		rml:functionExecution <#Execution1>;
	];
	rml:predicateObjectMap [
                rml:predicate foaf:name;
                rml:objectMap [
                      rml:reference "Name" ;
                ]
    ] .


<#Execution1>
    rml:function morph-kgc:concat ;
    rml:input
        [
            rml:parameter grel:valueParam1 ;
            rml:inputValueMap [
                rml:constant "https://data.eus/customer/"
            ];
        ] ,
        [
            rml:parameter grel:valueParam2 ;
            rml:inputValueMap [
                rml:functionExecution <#Execution2>
            ];
        ] .

<#Execution2>
    rml:function morph-kgc:uuid .
```

**uui-test.csv**
```csv
Id,Name,Comment,Class
1,M Venus,A&B,A
```

Eception:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 3629, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'object_map'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mikel/EHU-LSI/Investigacion/TransferenciaConocimientoEuskoiker/BASF/development/BASF_EKG_automatic_generation/Transformation/AirlinesCustomerSatisfactionCSV2RDF/Mappings/csv2rdf-morph-kgc-rdflib.py", line 7, in <module>
    graph = morph_kgc.materialize('uui-test.ini')
  File "/home/mikel/.local/lib/python3.10/site-packages/morph_kgc/__init__.py", line 64, in materialize
    triples = materialize_set(config, python_source)
  File "/home/mikel/.local/lib/python3.10/site-packages/morph_kgc/__init__.py", line 39, in materialize_set
    rml_df, fno_df = retrieve_mappings(config)
  File "/home/mikel/.local/lib/python3.10/site-packages/morph_kgc/mapping/mapping_parser.py", line 26, in retrieve_mappings
    rml_df, fno_df = mappings_parser.parse_mappings()
  File "/home/mikel/.local/lib/python3.10/site-packages/morph_kgc/mapping/mapping_parser.py", line 414, in parse_mappings
    self._get_from_r2_rml()
  File "/home/mikel/.local/lib/python3.10/site-packages/morph_kgc/mapping/mapping_parser.py", line 445, in _get_from_r2_rml
    data_source_rml_df, data_source_fno_df = self._parse_data_source_mapping_files(section_name)
  File "/home/mikel/.local/lib/python3.10/site-packages/morph_kgc/mapping/mapping_parser.py", line 495, in _parse_data_source_mapping_files
    return _transform_mappings_into_dataframe(mapping_graph, section_name)
  File "/home/mikel/.local/lib/python3.10/site-packages/morph_kgc/mapping/mapping_parser.py", line 301, in _transform_mappings_into_dataframe
    rml_df['object_join_conditions'] = rml_df['object_map'].map(join_conditions_dict)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 3631, in get_loc
    raise KeyError(key) from err
KeyError: 'object_map'
```

Thanks

Regards

**Comment by mikel-egana-aranguren** [comment]
Yes, I was using the wrong version (2.5), upgrading to v2.6.1 made it work

Thanks!
