### ISSUE TITLE
missing 1 required positional argument

### ISSUE THREAD

**Issue by leonqli** [morph-kgc/morph-kgc#193]
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/leonqli/.local/lib/python3.10/site-packages/morph_kgc/__main__.py", line 45, in <module>
    num_triples = sum(pool.starmap(_materialize_mapping_group_to_file,
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
TypeError: to_upper_case() missing 1 required positional argument: 'string'

```

**Comment by arenas-guerrero-julian** [comment]
Hi @leonqli ,

Could you please share the mapping?
