### ISSUE TITLE
Named graphs with blank nodes trigger "Exception: list indices must be integers or slices, not str"

### ISSUE THREAD

**Issue by Stiksels** [morph-kgc/morph-kgc#202]
####  What Happens?
I am trying to generate a n-quads file. When I run morpg_kgc with the sample below, I get an error. When I run the same sample but the graphs commented out (`#graphs: exp:$(participantUuid)`) , it works but creates a n-triples file

Error message stacktrace:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/morph_kgc/mapping/mapping_parser.py", line 530, in _parse_data_source_mapping_files
    mapping_graph += load_yarrrml(f)
                     ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/morph_kgc/mapping/yarrrml.py", line 556, in load_yarrrml
    yarrrml_mapping = _normalize_yarrrml_mapping(yarrrml_mapping)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/morph_kgc/mapping/yarrrml.py", line 266, in _normalize_yarrrml_mapping
    mapping_value['predicateobjects']['graphs'] = mapping_value['graphs']
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/morph_kgc/__main__.py", line 31, in <module>
    rml_df, fnml_df = retrieve_mappings(config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/morph_kgc/mapping/mapping_parser.py", line 21, in retrieve_mappings
    rml_df, fnml_df = mappings_parser.parse_mappings()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/morph_kgc/mapping/mapping_parser.py", line 476, in parse_mappings
    self._get_from_r2_rml()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/morph_kgc/mapping/mapping_parser.py", line 507, in _get_from_r2_rml
    data_source_rml_df, data_source_fnml_df = self._parse_data_source_mapping_files(section_name)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/morph_kgc/mapping/mapping_parser.py", line 532, in _parse_data_source_mapping_files
    raise Exception(yaml_parse_exception)
Exception: list indices must be integers or slices, not str
```

#### To Reproduce
run `python3 -m morph_kgc` with the files provided:

config_yatter-test.ini
```
[CONFIGURATION]
output_file: output/kg_yatter-test.nq
output_format: N-QUADS
[DataSource1]
mappings: yarrrml/yatter-test.yml
```

yatter-test.yml
```
# Define namespace prefixes for commonly used ontologies
prefixes:
  exp: "http://example.org/participant/"
  rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
  rdfs: "http://www.w3.org/2000/01/rdf-schema#"
  xsd: "http://www.w3.org/2001/XMLSchema#"
  dcterms: "http://purl.org/dc/terms/"
  grel: "http://users.ugent.be/~bjdmeest/function/grel.ttl#"
  skos: "http://www.w3.org/2004/02/skos/core#"
  wegwijs: "https://data.vlaanderen.be/id/organisatie/"
  adms: "http://www.w3.org/ns/adms#"
  cp: "https://data.vlaanderen.be/ns/cultuurparticipatie#"

# Define the mapping rules
mappings:

  # Mapping for 'participants' data
  participants:
    # Define sources to extract data from JSON
    sources:
      - ['data/yatter-test.csv~csv']
    #add triples to named-graph
    graphs: exp:$(participantUuid)
    # Define subject mapping
    s: exp:$(participantUuid)
    # Define predicate-object mappings
    po:
      - [a, cp:Participant]
      - [dcterms:created, $(created), xsd:dateTime]
      - [dcterms:modified, $(modified), xsd:dateTime]
      - p: adms:identifier
        o: 
          type: blank
          mapping: identificator
          condition:
            function: equal
            parameters:
              - [str1, $(participantUuid), s]
              - [str2, $(participantUuid), o]

  # Mapping for 'identificator' data
  identificator:
    sources:
      - ['data/yatter-test.csv~csv']
    #add triples to named-graph
    graphs: exp:$(participantUuid)
    # Define subject as null, indicating a blank node will be generated
    #s: null
    # Define predicate-object mappings
    po:
      - [a, adms:Identifier] 
      - [skos:notation, exp:$(participantUuid), xsd:anyURI]
      - [dcterms:creator, wegwijs:OVO026559~iri]
```

yatter-test.csv
```
participantUuid,created,modified
493b78b8-efa7-45b8-af5f-ca08ec90179e,2023-06-06T15:17:32.954+0000,2023-06-06T15:19:14.358+0000
ea9ba26f-e283-42a2-b57a-55ea3f5571ff,2022-12-28T14:46:03.682+0000,2022-12-28T14:48:23.17+0000
e0f5d6b0-984d-4192-b00f-8a07d2189712,2023-06-06T17:36:44.39+0000,2023-06-06T17:36:44.396+0000
20a15803-ca0e-42f9-9abe-93dc5d593a31,2022-12-16T11:39:39.481+0000,2022-12-16T11:43:58.073+0000
```

#### Expected outcome
a nq file like this is generated 
[yatter-test.nq.txt](https://github.com/morph-kgc/morph-kgc/files/13558629/yatter-test.nq.txt)

**Comment by Stiksels** [comment]
Update to issue stated above: when I use the key `graph` of the shortcut `g` the error is not triggered when running morph-kgc, but the generated output format is always ntriples and should be nquads.

As stated in the YARRRML specs, the key `graphs` should work (https://rml.io/yarrrml/spec/#graphs)

**Comment by arenas-guerrero-julian** [comment]
Hi @Stiksels ,

The default generation format is N-TRIPLES. You can set it to N-QUADS by setting the following in the congig file:

```
[CONFIGURATION]
output_format=N-QUADS
```

**Comment by Stiksels** [comment]
hi @arenas-guerrero-julian , thanks for the reply. I have tried your proposed solution with `output_format=N-QUADS` instead of `output_format: N-QUADS` , but I keep getting output in N-TRIPLES. Can you provide an example where morph-kgc takes a YARRML.yml file and outputs N-QUADS?

**Comment by Stiksels** [comment]
Hi @arenas-guerrero-julian , thank you for your swift response! I am, however, still unable to use morph-kgc with YARRRML to  generate a N-QUADS file.

I got morph-kgc to generate a N-QUADS file by using a RML file generated by yatter:

`python3 -m yatter -i yarrrml/yatter-test.yml -o RML/yatter-test_rml.ttl`

```@prefix rr: <http://www.w3.org/ns/r2rml#>.
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix fnml: <http://semweb.mmlab.be/ns/fnml#>.
@prefix fno: <https://w3id.org/function/ontology#>.
@prefix d2rq: <http://www.wiwiss.fu-berlin.de/suhl/bizer/D2RQ/0.1#>.
@prefix void: <http://rdfs.org/ns/void#>.
@prefix dc: <http://purl.org/dc/terms/>.
@prefix foaf: <http://xmlns.com/foaf/0.1/>.
@prefix rml: <http://semweb.mmlab.be/ns/rml#>.
@prefix ql: <http://semweb.mmlab.be/ns/ql#>.
@prefix : <http://mapping.example.com/>.
@prefix exp: <http://example.org/participant/>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.
@prefix dcterms: <http://purl.org/dc/terms/>.
@prefix grel: <http://users.ugent.be/~bjdmeest/function/grel.ttl#>.
@prefix skos: <http://www.w3.org/2004/02/skos/core#>.
@prefix wegwijs: <https://data.vlaanderen.be/id/organisatie/>.
@prefix adms: <http://www.w3.org/ns/adms#>.
@prefix cp: <https://data.vlaanderen.be/ns/cultuurparticipatie#>.

:rules_000 a void:Dataset;
    void:exampleResource :map_participants_000.
:map_participants_000 rml:logicalSource :source_000.
:source_000 a rml:LogicalSource;
    rml:source "data/yatter-test.csv";
    rml:referenceFormulation ql:CSV.
:map_participants_000 a rr:TriplesMap;
    rdfs:label "participants".
:s_000 a rr:SubjectMap.
:map_participants_000 rr:subjectMap :s_000.
:s_000 rr:template "http://example.org/participant/{participantUuid}";
    rr:graphMap :gm_000.
:gm_000 a rr:GraphMap;
    rr:template "http://example.org/participant/{participantUuid}".
:pom_000 a rr:PredicateObjectMap.
:map_participants_000 rr:predicateObjectMap :pom_000.
:pm_000 a rr:PredicateMap.
:pom_000 rr:predicateMap :pm_000.
:pm_000 rr:constant rdf:type.
:pom_000 rr:objectMap :om_000.
:om_000 a rr:ObjectMap;
    rr:constant cp:Participant;
    rr:termType rr:IRI.
:pom_001 a rr:PredicateObjectMap.
:map_participants_000 rr:predicateObjectMap :pom_001.
:pm_001 a rr:PredicateMap.
:pom_001 rr:predicateMap :pm_001.
:pm_001 rr:constant dcterms:created.
:pom_001 rr:objectMap :om_001.
:om_001 a rr:ObjectMap;
    rml:reference "created";
    rr:termType rr:Literal;
    rr:datatype xsd:dateTime.
:pom_002 a rr:PredicateObjectMap.
:map_participants_000 rr:predicateObjectMap :pom_002.
:pm_002 a rr:PredicateMap.
:pom_002 rr:predicateMap :pm_002.
:pm_002 rr:constant dcterms:modified.
:pom_002 rr:objectMap :om_002.
:om_002 a rr:ObjectMap;
    rml:reference "modified";
    rr:termType rr:Literal;
    rr:datatype xsd:dateTime.
:pom_003 a rr:PredicateObjectMap.
:map_participants_000 rr:predicateObjectMap :pom_003.
:pm_003 a rr:PredicateMap.
:pom_003 rr:predicateMap :pm_003.
:pm_003 rr:constant adms:identifier.
:rules_000 void:exampleResource :map_identificator_000.
:map_identificator_000 rml:logicalSource :source_001.
:source_001 a rml:LogicalSource;
    rml:source "data/yatter-test.csv";
    rml:referenceFormulation ql:CSV.
:map_identificator_000 a rr:TriplesMap;
    rdfs:label "identificator".
:s_001 a rr:SubjectMap.
:map_identificator_000 rr:subjectMap :s_001.
:s_001 rr:template "http://example.org/participant/$(participantUuid)#identifier";
    rr:graphMap :gm_001.
:gm_001 a rr:GraphMap;
    rr:template "http://example.org/participant/{participantUuid}".
:pom_004 a rr:PredicateObjectMap.
:map_identificator_000 rr:predicateObjectMap :pom_004.
:pm_004 a rr:PredicateMap.
:pom_004 rr:predicateMap :pm_004.
:pm_004 rr:constant rdf:type.
:pom_004 rr:objectMap :om_003.
:om_003 a rr:ObjectMap;
    rr:constant adms:Identifier;
    rr:termType rr:IRI.
:pom_005 a rr:PredicateObjectMap.
:map_identificator_000 rr:predicateObjectMap :pom_005.
:pm_005 a rr:PredicateMap.
:pom_005 rr:predicateMap :pm_005.
:pm_005 rr:constant skos:notation.
:pom_005 rr:objectMap :om_004.
:om_004 a rr:ObjectMap;
    rr:template "http://example.org/participant/{participantUuid}";
    rr:termType rr:Literal;
    rr:datatype xsd:anyURI.
:pom_006 a rr:PredicateObjectMap.
:map_identificator_000 rr:predicateObjectMap :pom_006.
:pm_006 a rr:PredicateMap.
:pom_006 rr:predicateMap :pm_006.
:pm_006 rr:constant dcterms:creator.
:pom_006 rr:objectMap :om_005.
:om_005 a rr:ObjectMap;
    rr:constant wegwijs:OVO026559;
    rr:termType rr:IRI.
:pom_003 rr:objectMap :om_006.
:om_006 a rr:ObjectMap;
    rr:parentTriplesMap :map_identificator_000;
    rr:joinCondition :jc_000.
:jc_000 rr:child "participantUuid";
    rr:parent "participantUuid".
```

output:
```
<exp:ea9ba26f-e283-42a2-b57a-55ea3f5571ff#identifier> <http://purl.org/dc/terms/creator> <https://data.vlaanderen.be/id/organisatie/OVO026559> <exp:ea9ba26f-e283-42a2-b57a-55ea3f5571ff> .
<exp:493b78b8-efa7-45b8-af5f-ca08ec90179e#identifier> <http://purl.org/dc/terms/creator> <https://data.vlaanderen.be/id/organisatie/OVO026559> <exp:493b78b8-efa7-45b8-af5f-ca08ec90179e> .
<exp:e0f5d6b0-984d-4192-b00f-8a07d2189712#identifier> <http://purl.org/dc/terms/creator> <https://data.vlaanderen.be/id/organisatie/OVO026559> <exp:e0f5d6b0-984d-4192-b00f-8a07d2189712> .
```

**Comment by arenas-guerrero-julian** [comment]
Hi @Stiksels ,

I think I fixed this. I have tried myself and it is working. Please, install from source and let me know if it also works for you.
