### ISSUE TITLE
YARRRML external references

### ISSUE THREAD

**Issue by david-martinez-garcia** [morph-kgc/morph-kgc#243]
Hello.

Are YARRRML external references supported in Morph-KGC? According to the specification, it is possible to define some sort of "constant" data outside of a data source: [https://rml.io/yarrrml/spec/#external-references](https://rml.io/yarrrml/spec/#external-references).

I have tried to define these references in a mappings file but Morph raises the following exception:

```bash
user@machine:~/directory$ python3 -m morph_kgc config.ini
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/morph_kgc/mapping/mapping_parser.py", line 530, in _parse_data_source_mapping_files
    mapping_graph += load_yarrrml(f)
  File "/home/user/.local/lib/python3.10/site-packages/morph_kgc/mapping/yarrrml.py", line 562, in load_yarrrml
    yarrrml_mapping = _normalize_yarrrml_mapping(yarrrml_mapping)
  File "/home/user/.local/lib/python3.10/site-packages/morph_kgc/mapping/yarrrml.py", line 236, in _normalize_yarrrml_mapping
    if type(mapping_value['sources']) is list:
KeyError: 'sources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/.local/lib/python3.10/site-packages/morph_kgc/__main__.py", line 32, in <module>
    rml_df, fnml_df = retrieve_mappings(config)
  File "/home/user/.local/lib/python3.10/site-packages/morph_kgc/mapping/mapping_parser.py", line 21, in retrieve_mappings
    rml_df, fnml_df = mappings_parser.parse_mappings()
  File "/home/user/.local/lib/python3.10/site-packages/morph_kgc/mapping/mapping_parser.py", line 476, in parse_mappings
    self._get_from_r2_rml()
  File "/home/user/.local/lib/python3.10/site-packages/morph_kgc/mapping/mapping_parser.py", line 507, in _get_from_r2_rml
    data_source_rml_df, data_source_fnml_df = self._parse_data_source_mapping_files(section_name)
  File "/home/user/.local/lib/python3.10/site-packages/morph_kgc/mapping/mapping_parser.py", line 532, in _parse_data_source_mapping_files
    raise Exception(yaml_parse_exception)
Exception: 'sources'
```

I think the problem is that Morph is expecting sources for the mapping, but in the examples provided in the specification no sources are defined.

Thank you.

**Comment by arenas-guerrero-julian** [comment]
This is not supported. Actually I did not know about external references. Implementing them should not be difficult.
