### ISSUE TITLE
Issue with use of functions in YARRRML configuration

### ISSUE THREAD

**Issue by IshanDindorkar** [morph-kgc/morph-kgc#244]
Hello,

We are currently trying to use Python-based functions to do data pre-processing while loading it from relational database for e.g. Oracle. We tried integrating it with the YARRRML configuration and had some success using below mapping file

```
prefixes:
  ont: "http://example.com/"
  grel: "http://users.ugent.be/~bjdmeest/function/grel.ttl#"

sources:
  cmdb:
    queryFormulation: sql2016
    query: SELECT ID, FIELD_1, FIELD_2, FIELD_3 FROM cmswhs.v_spl_h_item WHERE ROWNUM < 10

mappings:
  plant:
    sources: source
    s: http://example.com/$(ID)
    po:
      - [a, ont:Company]
      - [ont:companyName, $(FIELD_1)]
      - p: ont:hasAsset
        o:
        - mapping: asset
        - function: ex:toLowerCase
          parameters:
            - parameter: grel:valueParam
              value: $(FIELD_2)

  asset:
    sources: source
    s: http://example.com/$(FIELD_2)
    po:
      - [ a, ont:Asset ]
```
However, if I replace `asset` configuration with below lines

```
asset:
    sources: source
    s: http://example.com/$(FIELD_2)
    po:
      - [ a, ont:Asset ]
      - p: ont:assetName
        o:
        - function: ex:toLowerCase
          parameters:
            - parameter: grel:valueParam
              value: $(FIELD_3)
```
then, we are facing following error:

```
Traceback (most recent call last):
  File "/home/<user>/product_workspace/product/product-core/examples/data_sources/oracle/oracle_2_rdf.py", line 94, in <module>
    main()
  File "/home/<user>/product_workspace/product/product-core/examples/data_sources/oracle/oracle_2_rdf.py", line 87, in main
    kg = load_kg_data(config=config)
  File "/home/<user>/product_workspace/product/product-core/examples/data_sources/oracle/oracle_2_rdf.py", line 55, in load_kg_data
    kg = kg.materialize(config)
  File "/home/<user>/miniconda3/envs/product_core_env_3_10_20240227/lib/python3.10/site-packages/kglab/serde.py", line 575, in materialize
    self._g = morph_kgc.materialize(config)
  File "/home/<user>/miniconda3/envs/product_core_env_3_10_20240227/lib/python3.10/site-packages/morph_kgc/__init__.py", line 65, in materialize
    triples = materialize_set(config, python_source)
  File "/home/<user>/miniconda3/envs/product_core_env_3_10_20240227/lib/python3.10/site-packages/morph_kgc/__init__.py", line 39, in materialize_set
    rml_df, fnml_df = retrieve_mappings(config)
  File "/home/<user>/miniconda3/envs/product_core_env_3_10_20240227/lib/python3.10/site-packages/morph_kgc/mapping/mapping_parser.py", line 21, in retrieve_mappings
    rml_df, fnml_df = mappings_parser.parse_mappings()
  File "/home/<user>/miniconda3/envs/product_core_env_3_10_20240227/lib/python3.10/site-packages/morph_kgc/mapping/mapping_parser.py", line 476, in parse_mappings
    self._get_from_r2_rml()
  File "/home/<user>/miniconda3/envs/product_core_env_3_10_20240227/lib/python3.10/site-packages/morph_kgc/mapping/mapping_parser.py", line 507, in _get_from_r2_rml
    data_source_rml_df, data_source_fnml_df = self._parse_data_source_mapping_files(section_name)
  File "/home/<user>/miniconda3/envs/product_core_env_3_10_20240227/lib/python3.10/site-packages/morph_kgc/mapping/mapping_parser.py", line 564, in _parse_data_source_mapping_files
    _validate_termtypes(mapping_graph)
  File "/home/<user>/miniconda3/envs/product_core_env_3_10_20240227/lib/python3.10/site-packages/morph_kgc/mapping/mapping_parser.py", line 431, in _validate_termtypes
    raise ValueError(f'Found an invalid predicate termtype. Found values {predicate_termtypes}. '
ValueError: Found an invalid predicate termtype. Found values {'http://w3id.org/rml/Literal', 'http://w3id.org/rml/IRI'}. Predicate maps must be http://w3id.org/rml/IRI.
```

Could you please help us in fixing this issue or provide suitable direction to start looking into.

Thank you.

Sincerely,
Ishan Dindorkar

**Comment by IshanDindorkar** [comment]
Thank you @arenas-guerrero-julian for your prompt response. Your advice helped us in fixing the issue.
