### ISSUE TITLE
Transforming Parquet file with non-null empty strings rises error

### ISSUE THREAD

**Issue by KappaGi** [morph-kgc/morph-kgc#261]
####  What Happens?

I am running Morph with correct mapping file over Parquet source file specified in config.ini using file_path .
The Parquet source file contains two types of values to consider as null:

- Null values that are None if being inspected using pyarrow -> to pandas dataframe  or -> to pydict
- Empty non-null strings ('') if being inspected in the same way.

Example of row containing both type of values:
`Pandas(Index=1197, C1='', C2=None) `

I am using `na_values:None,,nan` in config file. However, if the source file contains empty non-null strings ('') like the one for column C1 before, I get the following error:

> multiprocessing.pool.RemoteTraceback:                                                                              
> """                                                                                                                
> Traceback (most recent call last):                                                                                 
>   File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 125, in worker
>     result = (True, func(*args, **kwds))
>   File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 51, in starmapstar
>     return list(itertools.starmap(args[0], args[1]))
>   File "C:\Users\user\Projects\my_project\venv\lib\site-packages\morph_kgc\materializer.py", line 344, in _materialize_m
> apping_group_to_file
>     data = _materialize_rml_rule(rml_rule, rml_df, fnml_df, config)
>   File "C:\Users\user\Projects\my_project\venv\lib\site-packages\morph_kgc\materializer.py", line 312, in _materialize_r
> ml_rule
>     data = _materialize_rml_rule_terms(data, rml_rule, fnml_df, config)
>   File "C:\Users\user\Projects\my_project\venv\lib\site-packages\morph_kgc\materializer.py", line 183, in _materialize_r
> ml_rule_terms
>     results_df = _materialize_fnml_execution(results_df, rml_rule['subject_map_value'], fnml_df, config, 'subject',
>   File "C:\Users\user\Projects\my_project\venv\lib\site-packages\morph_kgc\materializer.py", line 171, in _materialize_f
> nml_execution
>     results_df[position] = '<' + results_df[fnml_execution] + '>'
>   File "C:\Users\user\Projects\my_project\venv\lib\site-packages\pandas\core\ops\common.py", line 76, in new_method     
>     return method(self, other)
>   File "C:\Users\user\Projects\my_project\venv\lib\site-packages\pandas\core\arraylike.py", line 190, in __radd__       
>     return self._arith_method(other, roperator.radd)
>   File "C:\Users\user\Projects\my_project\venv\lib\site-packages\pandas\core\series.py", line 6115, in _arith_method    
>     return base.IndexOpsMixin._arith_method(self, other, op)
>   File "C:\Users\user\Projects\my_project\venv\lib\site-packages\pandas\core\base.py", line 1382, in _arith_method      
>     result = ops.arithmetic_op(lvalues, rvalues, op)
>   File "C:\Users\user\Projects\my_project\venv\lib\site-packages\pandas\core\ops\array_ops.py", line 283, in arithmetic_
> op
>     res_values = _na_arithmetic_op(left, right, op)  # type: ignore[arg-type]
>   File "C:\Users\user\Projects\my_project\venv\lib\site-packages\pandas\core\ops\array_ops.py", line 218, in _na_arithme
> tic_op
>     result = func(left, right)
>   File "C:\Users\user\Projects\my_project\venv\lib\site-packages\pandas\core\roperator.py", line 11, in radd
>     return right + left
> numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U1'), dtype(
> 'float64')) -> None
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\user\Projects\my_project\venv\lib\site-packages\morph_kgc\__main__.py", line 47, in <module>
>     num_triples = sum(pool.starmap(_materialize_mapping_group_to_file,
>   File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 375, in starmap
>     return self._map_async(func, iterable, starmapstar, chunksize).get()
>   File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 774, in get
>     raise self._value
> numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U1'), dtype(
> 'float64')) -> None
> 

I expected na_values to work with `,,` value. Obviously, If I ommit this value in na_values the error is not shown and I get empty values in output triples.

Do you think there is any solution to this issue? I don't want to cast or transform my data, nor use rml view (duckdb) to solve this problem.

To give some extra information, If I use pyarrow.parquet.read_table and print info I get:
```
C1: string not null
C2: string
```

Whereas if I use pyarrow.parquet.ParquetFile.schema I get:
```
required binary field_id=-1 C1(String);
optional binary field_id=-1 C2(String);
```

Regards.

#### Environment:
 - OS: [e.g. Windows 10
 - Python version: 3.10.11
 - Morph-KGC version: 2.8.0

**Comment by arenas-guerrero-julian** [comment]
`,,` in `na_values` should work. Could you attach some minimal example (parquet file and mapping) to look into this?

**Comment by KappaGi** [comment]
Hello,

Thanks for the answer. I have tested in a specific mapping file wihtout success. But let me add more information to the issue I have compiled in simle experiments.

Let's say I have two parquet files with three columns. One of the files have column 2 with empty strings, the another has column 2 with null values:

- File `generated_empty.parquet`
```
C1: [["1","2","3"]]
C2: [["","",""]]
C3: [["A","B","C"]]
```

- File `generated_null.parquet`
```
C1: [["1","2","3"]]
C2: [[null,null,null]]
C3: [["A","B","C"]]
```

Now, I have two mapping files. One that uses the execution of a concat function to generate subjects, another that uses template to generate subjects.

- Mapping file `mapping_concat.ttl`:

```
@prefix rr: <http://www.w3.org/ns/r2rml#>.
@prefix rml: <http://semweb.mmlab.be/ns/rml#>.
@prefix grel: <http://users.ugent.be/~bjdmeest/function/grel.ttl#> .
@prefix fnml: <http://semweb.mmlab.be/ns/fnml#>.
@prefix morph-kgc: <https://github.com/morph-kgc/morph-kgc/function/built-in.ttl#>.
@prefix : <http://www.w3.org/example#>.

:AdverseEventsMap1 a rr:TriplesMap;
    rml:logicalSource [];
    rr:subjectMap [
        fnml:execution :Execution;
        rr:termType rr:IRI;
        rr:class <urn:class>;
    ];
    rr:predicateObjectMap [
        rr:predicate <urn:predicate>;
        rr:objectMap [
            rr:column "C2";
        ]
    ];
    rr:predicateObjectMap [
        rr:predicate <urn:predicate>;
        rr:objectMap [
            rr:column "C3";
        ]
    ];
.

:Execution
    fnml:function morph-kgc:concat ;
        fnml:input
            [
                fnml:parameter grel:valueParam1 ;
                fnml:value "urn:"
            ];
        fnml:input
            [
                fnml:parameter grel:valueParam2 ;
                fnml:valueMap [
                    rml:reference "C1" ;
				]
            ];
.
```

- Mapping file `mapping.ttl
`
```
@prefix rr: <http://www.w3.org/ns/r2rml#>.
@prefix rml: <http://semweb.mmlab.be/ns/rml#>.
@prefix grel: <http://users.ugent.be/~bjdmeest/function/grel.ttl#> .
@prefix fnml: <http://semweb.mmlab.be/ns/fnml#>.
@prefix morph-kgc: <https://github.com/morph-kgc/morph-kgc/function/built-in.ttl#>.
@prefix : <http://www.w3.org/example#>.

:AdverseEventsMap1 a rr:TriplesMap;
    rml:logicalSource [];
    rr:subjectMap [
        rr:template "urn:{C1}";
        rr:termType rr:IRI;
        rr:class <urn:class>;
    ];
    rr:predicateObjectMap [
        rr:predicate <urn:predicate>;
        rr:objectMap [
            rr:column "C2";
        ]
    ];
    rr:predicateObjectMap [
        rr:predicate <urn:predicate>;
        rr:objectMap [
            rr:column "C3";
        ]
    ];
.
```

And I have a base configuration with default na_values, that I can use to switch between one of the previous mapping / data files. 
```
[CONFIGURATION]
output_file: kg_file.nt

[DataSource0]
mappings: {mapping-file}
file_path: {parquet-file}
```

If I run Morph with `mapping.ttl` and `generated_empty.parquet` I get expected result:

```
<urn:2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <urn:class> .
<urn:1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <urn:class> .
<urn:3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <urn:class> .
<urn:1> <urn:predicate> "A" .
<urn:3> <urn:predicate> "C" .
<urn:2> <urn:predicate> "B" .
```

Nevertheless, using `mapping_concat.ttl` and `generated_empty.parquet` I get exception and unexpected results:

> numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U1'), dtype(
> 'float64')) -> None

```
<urn:2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <urn:class> .
<urn:3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <urn:class> .
<urn:1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <urn:class> .
```

If I run Morph with `mapping.ttl` or `mapping_concat.ttl` and `generated_null.parquet` I get unexpected result:

```
<urn:2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <urn:class> .
<urn:1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <urn:class> .
<urn:3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <urn:class> .
<urn:3> <urn:predicate> "C" .
<urn:2> <urn:predicate> "None" .
<urn:2> <urn:predicate> "B" .
<urn:1> <urn:predicate> "None" .
<urn:1> <urn:predicate> "A" .
<urn:3> <urn:predicate> "None" .
```

In this last run, If I add `na_values:,nan,None` to the configuration, I get expected results. But this is not a good solution since I might have a file like:
```
C1: [["1","2","3"]]
C2: [[null,null,null]]
C3: [["None","Single","Double"]]
```
And I won't be generating triples for all values of column C3.

So from my point of view I see two issues:

Issue 1. I can't use concat function to define subjects if my parquet file contains empty strings (even if the empty string values are not used in the concatenation function). Of course in this mapping example there is a workaround but not for concatenations of the results of other functions, for example.

Issue 2. I can't differentiate between null values and "None" string in my parquet file, because I am forced to add `None `to `na_values`.

What do you think?

I left the files in the example in case you want to perform some tests.

Thanks for your support.

[morph_issue_261.zip](https://github.com/user-attachments/files/15927169/morph_issue_261.zip)

**Comment by KappaGi** [comment]
Dear @arenas-guerrero-julian ,

I have updated my previous comment trying to clarify what happened, sorry to introduced some noise initially. In summary, I can see three issues:

<b>Issue 1.</b> I can't use concat function to define subjects if my parquet file contains empty strings (even if the empty string values are not used in the concatenation function). Of course in this mapping example there is a workaround but not for concatenations of the results of other functions, for example.

<b>Issue 2.</b> I can't differentiate between null values and "None" string in my parquet file, because I am forced to add None to na_values to handle actual null values properly.

<b>Issue3.</b> Error is raisen when transforming a parquet file having all values of (at least) one column equal to null. Even if I add `na_values:,nan,None` to the configuration. In any case, it seems I get appropriate triples generated. Hence, it is hard to recognise if there has been actually any problem during transformation.

About <b>Issue3.</b>, I have already tested:

- Use RML view (rml:query) to load the parquet file using duckdb. Problem persists.
- Convert file to CSV. Problem persists having `na_values:,nan,None` in the configuration.

That makes me think that the only workaround is to pre-process mapping files by deleting the predicate object maps which make reference to a column name that has all values equal to null in source data.

Kind regards.

**Comment by KappaGi** [comment]
Hello @arenas-guerrero-julian, 

Does the previous message seem relevant to you? Are these issues something you can reproduce? 

Please let me know if I can provide more information.

Regards.
